// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvuuGn25L_foGpa5lkLFtGpNS2EBzDsOk',
    appId: '1:735227481276:web:73c2615a4434f03b4654b9',
    messagingSenderId: '735227481276',
    projectId: 'monkeyshop-5b345',
    authDomain: 'monkeyshop-5b345.firebaseapp.com',
    storageBucket: 'monkeyshop-5b345.firebasestorage.app',
    measurementId: 'G-QQ4QEWRDM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcdGqhqm_cQMxOxcTIojfzhdmbD7XD5v4',
    appId: '1:735227481276:android:7681bccd9c12da404654b9',
    messagingSenderId: '735227481276',
    projectId: 'monkeyshop-5b345',
    storageBucket: 'monkeyshop-5b345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLfdRxX0LY45CDmqJDy4yvTPuVptHbjM',
    appId: '1:735227481276:ios:9f061786b7c9ca114654b9',
    messagingSenderId: '735227481276',
    projectId: 'monkeyshop-5b345',
    storageBucket: 'monkeyshop-5b345.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeLfdRxX0LY45CDmqJDy4yvTPuVptHbjM',
    appId: '1:735227481276:ios:9f061786b7c9ca114654b9',
    messagingSenderId: '735227481276',
    projectId: 'monkeyshop-5b345',
    storageBucket: 'monkeyshop-5b345.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvuuGn25L_foGpa5lkLFtGpNS2EBzDsOk',
    appId: '1:735227481276:web:4444bb7fa138e7234654b9',
    messagingSenderId: '735227481276',
    projectId: 'monkeyshop-5b345',
    authDomain: 'monkeyshop-5b345.firebaseapp.com',
    storageBucket: 'monkeyshop-5b345.firebasestorage.app',
    measurementId: 'G-V21QMPK8KK',
  );
}
